version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/unc-dining
      - PYTHON_SERVICE_URL=http://python-service:5001
    depends_on:
      - mongodb
      - python-service

  python-service:
    build: ./python-service
    ports:
      - "5001:5001"
    volumes:
      - ./python-service:/app
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - PORT=5001

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
